// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lemgxfzcjxkvytzdbvak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlbWd4Znpjanhrdnl0emRidmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTIyMDAsImV4cCI6MjA3Mzg2ODIwMH0.028t-r3P4-hQBON5TGfdyFcPYH2h-jMc_PRwyl-sn_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});